### ISSUE TITLE
additional arguments for the objective function

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaOpt/NLopt.jl#100]
Is there any way to pass additional arguments to the objective function? My objective function relies on several fixed variables calculated elsewhere. At present they are in the global scope so the objective function can reach out and grab them but I'm not sure if this is affecting the efficiency. And as I will be including this as part of a module I think it will complicate the design of the module slightly.

In particular, is there a way to access the "void* f_data" argument shown in the following link: https://nlopt.readthedocs.io/en/latest/NLopt_Reference/#objective-function

If not, is there interest in adding this as a feature?

**Comment by stevengj** [comment]
You can already do this using a closure.

See #27 and #7 ... it seems like this is the most common confusion with NLopt in high-level languages.  `f_data` is just a hack for languages like C that don't support closures.

**Comment by moustachio-belvedere** [comment]
Ah I understand now. Thanks for explaining. Maybe it's worth mentioning in the readme if a few people have been confused by it.
