### ISSUE TITLE
GN_ORIG_DIRECT segmentation fault

### ISSUE THREAD

**Issue by stumarcus576** [JuliaOpt/NLopt.jl#104]
I'm trying to use NLopt's derivative-free global optimization algorithms to minimize an objective function with 60 continuous, bounded, positive variables and 59 linear inequality constraints. The linear inequality constraints are imposed with the inequality_constraint option. If I use the GN_ISRES algorithm, NLopt runs. However if I use the GN_ORIG_DIRECT algorithm, NLopt halts early with a segmentation fault as shown below. I use Julia Version 0.6.2 running on macOS Sierra 10.12.6 (x86_64-apple-darwin14.5.0).

signal (11): Segmentation fault: 11
while loading /Users/a598124/juliaCode/boxPacking3/BSO_NLopt.jl, in expression starting on line 87
direct_dirreplaceinf_ at /Users/a598124/.julia/v0.6/Homebrew/deps/usr/lib/libnlopt.dylib (unknown line)
Allocations: 3751239 (Pool: 3749923; Big: 1316); GC: 4
Segmentation fault: 11

**Comment by Crown421** [comment]
I have a similar problem on Ubuntu 14.04. The code runs perfectly fine on macOs Mojave and Julia 1.2, but using Ubuntu and the same Julia version gives me a segfault.

```
signal (11): Segmentation fault
in expression starting at REPL[6]:1
direct_direct_ at /home/user/.julia/packages/NLopt/eqN9a/deps/usr/lib/libnlopt.so (unknown line)
direct_optimize at /home/user/.julia/packages/NLopt/eqN9a/deps/usr/lib/libnlopt.so (unknown line)
nlopt_optimize at /home/user/.julia/packages/NLopt/eqN9a/deps/usr/lib/libnlopt.so (unknown line)
```

I hacked NLopt.jl with the the new build.jl file provided in the NLopt 2.6.1 release, but unfortunately that did not help. 

Very happy about suggestions.

**Comment by stevengj** [comment]
Can you create a minimal reproducer?

The following works for me:
```jl
using NLopt

function myfunc(x::Vector, grad::Vector)
    if length(grad) > 0
        grad[1] = 0
        grad[2] = 0.5/sqrt(x[2])
    end
    return sqrt(x[2])
end

function myconstraint(x::Vector, grad::Vector, a, b)
    if length(grad) > 0
        grad[1] = 3a * (a*x[1] + b)^2
        grad[2] = -1
    end
    (a*x[1] + b)^3 - x[2]
end

opt = Opt(:GN_ORIG_DIRECT, 2)
opt.lower_bounds = [-10, 0]; opt.upper_bounds = [10,10]
opt.maxeval = 1000
opt.min_objective = myfunc
inequality_constraint!(opt, (x,g) -> myconstraint(x,g,2,0), 1e-8)
inequality_constraint!(opt, (x,g) -> myconstraint(x,g,-1,1), 1e-8)
(minf,minx,ret) = optimize(opt, [1.234, 5.678])
```

**Comment by Crown421** [comment]
I tried the minimal example from the README, just swapping out the algorithm. 
The problems occurs on a older machine with Ubuntu 14.04., but I have not been able to reproduce on Ubuntu 16.04. or Manjaro 18.04.
I am continuing to troubleshoot, and will report back once I learn something new.

**Comment by odow** [comment]
Closing as stale and non-reproducible.
