### ISSUE TITLE
NLopt ignoring stopval, tolerance

### ISSUE THREAD

**Issue by merubhanot** [JuliaOpt/NLopt.jl#107]
In doing a relatively involved optimization with NLopt, I find that it seems to ignore stopval!() and ftol_rel!(), though maxtime!() is working. I'm using the optimizer LN_COBYLA.

Based on the links below, I have some sense it may be about the optimizer or the constraints (though the inequality constraints don't seem to be violated at the value it returns at maxtime, which has a function value well smaller than the stopval), but wanted to check if it was a bug/known issue, or if there is some clear way to get the optimization to adhere to the stopval. 

https://stackoverflow.com/questions/34755612/unexpected-behaviour-of-ftol-abs-and-ftol-rel-in-nlopt
https://discourse.julialang.org/t/nlopt-stopval-and-termination-criteria/7333/2

**Comment by odow** [comment]
Closing as stale, and because there is no reproducible example. If anyone encounters this in future, please post on the community forum, https://discourse.julialang.org/c/domain/opt/13, and tag me `@odow`.
