### ISSUE TITLE
macOS 10.14 Mojave support

### ISSUE THREAD

**Issue by arnavs** [JuliaOpt/NLopt.jl#113]
When building this package on my machine, I get a `KeyError: key "10.14" not found`. Since I suspect a few people are using the public beta, it would be great to add this. I suspect you can just copy whatever the setting is for 10.13.

**Comment by ArnavSood** [comment]
Update: I installed the underlying library with homebrew and then changed the `deps/build.jl` file to read this. All tests pass. 

```
if is_apple()
    using Homebrew
    return true 
end
```

**Comment by stevengj** [comment]
I'm planning to switch over to BinaryBuilder, which will eliminate Homebrew errors.

**Comment by arnavs** [comment]
Perfect, thanks.

**Comment by arnavs** [comment]
@luis9 You would want to `brew install nlopt`, and then go into wherever this package is installed (`~/.julia/packages/...` probably), and edit the relevant file.
