### ISSUE TITLE
Tutorial example gives answer "type Opt has no field numevals"

### ISSUE THREAD

**Issue by frankhuettner** [JuliaOpt/NLopt.jl#120]
If I copy&paste the [example](https://github.com/JuliaOpt/NLopt.jl#tutorial), I get the output:
`type Opt has no field numevals`
I use Julia 0.6.4 in Windows with Jupyter. Same result in Juliabox, using version 0.6.2.

**Comment by stevengj** [comment]
The tutorial example requires the latest version, which runs on Julia 0.7 or later.
