### ISSUE TITLE
Use of NLopt for complex numbers

### ISSUE THREAD

**Issue by rkumar-slim** [JuliaOpt/NLopt.jl#121]
Hello,

I am trying to use NLopt for a non-linear problem where my unknown is complex in nature. I get this error. Can I use NLopt for complex numbers?

Best Regards,

 (minf, minx, ret) = optimize(opt, vec(Z))
ERROR: MethodError: no method matching optimize(::NLopt.Opt, ::Array{Complex{Float64},1})
Closest candidates are:
  optimize(::NLopt.Opt, ::AbstractArray{T<:Real,1}) where T<:Real at /d/home/rajivk/.julia/v0.6/NLopt/src/NLopt.jl:532

**Comment by stevengj** [comment]
The optimization parameters have to be real, but you can just make the parameters from the real and imaginary parts of the complex numbers: `reinterpret(Float64, vec(Z))`.
