### ISSUE TITLE
Tolerance-Value dependence of Output

### ISSUE THREAD

**Issue by ChrisLippiEdin** [JuliaOpt/NLopt.jl#124]
Hi,
I am running a loop over different parameter values whereas in each I use MMA to solve a problem involving an inequality constraint. However, at some parameter values (even if the assure that the constraint is never binding) the results start to become funny in a sense that they are not the max anymore (for a slight parameter change, results drop massively. I tested that the outputs are non-optimal). My code is
```
 function obj(x::Vector, grad::Vector)   
            if length(grad) > 0
                grad[1] = pa*((1 + β₁*x[2]^β₂)/(1 + β₁*x[2]^β₂ + α₁*μ[i] + α₂*μ[i]^2))*(Aa*s[j])^(1-γ)*γ*(x[1])^(γ-1) - (1+r)*q + q
                grad[2] = pa*β₁*β₂*(x[1])^(γ)*(Aa*s[j])^(1-γ)*μ[i]*(α₂*μ[i] + α₁)*x[2]^(β₂-1)/(β₁*x[2]^(β₂) + α₂*μ[i]^2 + α₁*μ[i] + 1)^(2) - (1+r)*pn 
            end
    
           return pa*((1 + β₁*x[2]^β₂)/(1 + β₁*x[2]^β₂ + α₁*μ[i] + α₂*μ[i]^2))*(Aa*s[j])^(1-γ)*(x[1])^γ - (1+r)*(q*x[1] + pn*x[2]) + q*x[1]
        end


     function myconstraint(x::Vector, grad::Vector)
          if length(grad) > 0
               grad[1] = -1*λ*q + (1+r)*q
             grad[2] = (1+r)*pn
          end
          -1* λ*q*x[1]  + (1+r)*(q*x[1] + pn*x[2] - g)
      end

        opt = Opt(:LD_MMA, 2)    #algorithm, dimensionality of problem
        lower_bounds!(opt, [0, 0])
        xtol_rel!(opt,1e-8)
        max_objective!(opt, obj)

       inequality_constraint!(opt, (x,grad) -> myconstraint(x,grad), 0)

        results = NLopt.optimize(opt, [1e-3, 1e-3])
```
When I change the tolerance values then it might work for some parameter values, but still not for others. Bottom line, I don't find a way to assure the solver does not fail to find the optimum consistently for all exogenous values.
Do you have any suggestions what might be the issue?

Thanks a lot and merry Christmas

**Comment by stevengj** [comment]
Have you checked your gradients, e.g. against ForwardDiff.jl, for some random points?  That is the most common source of problems.

**Comment by ChrisLippiEdin** [comment]
Thanks for the answer,

what do you exactly mean by checking the gradients? What I did is, I used forwardDiff to check the gradient around the optimal points that I only get when I played around with the tolerance values. The gradient exists and exhibits the correct values.
The gradient from NLopt, before playing around with the tolerance values, gives me an output that, obviously, gives me incorrect values (the gradient is not equal to the vector of marginal costs).

Thanks a lot!

**Comment by ChrisLippiEdin** [comment]
Thanks @mzaffalon 
I checked i) the gradient at the value what I before considered as non-optimal (non-profit maximizing) and ii) the gradient with a different tolerance value that is profit maximizing.
It turns out that both outputs give zero gradients and are therefore optimal. 
Is the problem then just an issue of local vs global optimum? If so, do you know how to fix that in a sense of finding global maxima?

Thank you very much and merry Christmas!

**Comment by mzaffalon** [comment]
Are you saying that you took a totally random value of `x` and obtained `grad=[0,0]`? Would you not conclude that there is something wrong in the way you compute the vector `grad` in your function `obj`?

**Comment by ChrisLippiEdin** [comment]
no, I am saying that when I calculate the gradient with, for instance, forwarddiff.jl and apply random values for x then I get some random value  that is not zero. However, for the two different values of x that I get from my optimization with different tolerance values, the gradient is in both cases essentially zero. Hence my conclusion of multiple equilibria.

**Comment by mzaffalon** [comment]
The list of global optimizers is [here](https://nlopt.readthedocs.io/en/latest/NLopt_Algorithms/#global-optimization) but I have never used them.

In Julia, you probably would like to call `opt = Opt(:GN_DIRECT_L, 2)` as explained in the [tutorial](https://github.com/JuliaOpt/NLopt.jl). Also see the list of algorithms https://github.com/JuliaOpt/NLopt.jl/blob/master/src/NLopt.jl#L29

**Comment by ChrisLippiEdin** [comment]
Thanks a lot, that is very helpful

**Comment by odow** [comment]
Closing as stale and because this doesn't look like an issue in NLopt.
