### ISSUE TITLE
Specifying subsidiary optimization algorithm for augumented Lagranian when using JuMP

### ISSUE THREAD

**Issue by TorkelE** [JuliaOpt/NLopt.jl#126]
I just do not think this is documented (or I haven't found it?). I want to use the Augumented Lagranian with JuMP, however, when I declare:
```julia
m = Model(solver = NLoptSolver(algorithm=:AUGLAG_EQ))
...
JuMP.solve(m)
```
I get the 
```
ArgumentError: invalid NLopt arguments: local optimizer must be specified for AUGLAG
```
error when I run `JuMP.solve(m)`. However, I have looked through the code and haven't found how to specify this as input to a model. I can do it for an `Opt` object, but I am not sure how to input these into JuMP.

**Comment by mirkobunse** [comment]
Hi! I just want to give this issue a push; I ran into the same problem.

**Comment by stevengj** [comment]
Yes, it seems like `struct NLoptSolver` really needs a recursive `localopt::NLoptSolver` field that it can use to instantiate a local optimization algorithm.

cc @blegat who contributed this code (#150).

**Comment by ko56** [comment]
I just ran into the same issue with JuMP 0.21.8.  Is there any workaround?
