### ISSUE TITLE
forced stop when minimizing x^2

### ISSUE THREAD

**Issue by anguschkan** [JuliaOpt/NLopt.jl#127]
I tried minimizing a simple function as a learning example:

```
function f(x)
    return x[1]^2+rand(Normal(0,0.001))
end

opt = Opt(:LD_MMA,1)
lower_bounds!(opt,-10.)
upper_bounds!(opt,10.)
xtol_rel!(opt,1e-4)
min_objective!(opt,f)
(minf,minx,ret) = optimize(opt,[-1.2])
```
I ended up getting ret = FORCED_STOP. I'm wondering if it's because I didn't specify nonlinear constraints? Could someone kindly point out what went wrong in my code? Thanks!!

**Comment by mzaffalon** [comment]
There are two errors:

- your definition of `f` has the wrong signature, and it should instead be `f(x::Vector, grad::Vector)`, see for instance [NLopt tutorial](https://github.com/JuliaOpt/NLopt.jl#tutorial);
- the algorithm MMA requires you to provide the gradient of the objective function.

Also, if you paste code, you should wrap it with three backticks.

**Comment by anguschkan** [comment]
What if I have function of which I don't know the derivative, and I would like to use a derivative-free method? Should I simply include grad as an argument of my function, and add
```
if length(grad)>0
    end
```
in the definition of my code?

**Comment by mzaffalon** [comment]
Have a look at the [derivative free algorithms](https://github.com/JuliaOpt/NLopt.jl#the-opt-type): `:LN_COBYLA` and `:LN_NELDERMEAD` are two of them.

(I cannot stress enough how good the documentation for NLopt and NLopt.jl is.)
