### ISSUE TITLE
MethodError for opt.initial_step

### ISSUE THREAD

**Issue by mzaffalon** [JuliaOpt/NLopt.jl#132]
No method is defined when invoking the `initial_step` property:
```
julia> using NLopt; opt = Opt(:LN_NELDERMEAD, 2);
julia> opt.initial_step
ERROR: MethodError: no method matching initial_step(::Opt)
```

Would
```
initial_step(o::Opt) = initial_step(o, zeros(Float64, ndims(o)))
```
fix it?

PS: I thought
```
initial_step(o::Opt) = initial_step(o, Vector{Float64}(undef, ndims(o)))
```
would work too, but the values I get make no sense.

**Comment by stevengj** [comment]
We could define `initial_step(o::Opt) = x -> initial_step(o, x)` so that you could do `opt.initial_step(x)`, I guess.  Or just remove the `initial_step` property.

**Comment by mzaffalon** [comment]
What is wrong with creating the temporary array in my proposal above?

By the way, I also [see](https://github.com/JuliaOpt/NLopt.jl/blob/master/src/NLopt.jl#L501) that you defined `opt.inequality_constraint = ...`, which sets the tolerance to 0. There are now two methods to define the constraints, using properties and the function call.

I find it a bit confusing having some methods being implemented as function calls only (e.g. `ndims(opt)`), some as get_property (e.g. `opt.min_objective = ...`) and some (e.g. `inequality_constraints`) exposing two different interfaces according to whether one passes the tolerance.

Yes, I know that I can call `min_objective(opt, ...)` as before.

**Comment by stevengj** [comment]
> What is wrong with creating the temporary array in my proposal above?

Because the initial step in general depends on the initial guess vector, and there is no reason that initial guess vector should be the zero vector.

**Comment by mzaffalon** [comment]
I forgot about that.
