### ISSUE TITLE
tracing

### ISSUE THREAD

**Issue by HarlanH** [JuliaOpt/NLopt.jl#16]
Hi, this package works well for something I'm working on! But I wonder if it'd be possible to get support for tracing, ala the store_trace/show_trace options in Optim.jl. I can sorta fake it by adding print statements to my evaluation function, but that's obviously not a great solution. 

Skimming through the NLopt docs, I'm not actually sure if this is possible, but if it is, it'd be a great-to-have. Thanks!

**Comment by odow** [comment]
There hasn't been any activity on this issue for 10 years, so I'm going to close it. We're obviously doing okay with adding print statements to the objective function.
