### ISSUE TITLE
bogus FORCED_STOP, optx outside bounds with BOBYQA

### ISSUE THREAD

**Issue by tpapp** [JuliaOpt/NLopt.jl#161]
Sorry, can't provide an MWE (this happens in a 10k LOC problem), but with BOBYQA, I occasionally get a `ret = FORCED_STOP` without having requested one, with `optf = 0.0` which is not the value that corresponds to `optx`. Also one element of `optx` is eps below the lower bound (`0.9999999999999999 < 1`).

**Comment by odow** [comment]
Not sure this is debuggable without a MWE. Any luck since? If no MWE, I'll close this issue.

**Comment by tpapp** [comment]
Sorry, could not boil it down to an MWE. Feel free to close if you prefer that.
