### ISSUE TITLE
NLopt with JuMP puts out-of-bounds value into objective function before optimizing.

### ISSUE THREAD

**Issue by JGSuw** [JuliaOpt/NLopt.jl#170]
Hello,

I noticed that, before optimization begins, NLopt calls the objective function (call it `f(x)`) with the entries of `x` all zeros, even if this value of `x` is not feasible or otherwise within the bounds of the problem.

This has caused issues for me because I have a very complex optimization problem and my objective function breaks if certain of the decision variables are zero.

Below is a minimal example:

```julia
using NLopt
using JuMP

f(x) = begin
    @assert(x!=zero(eltype(x)))
    1/x
end

model = Model(NLopt.Optimizer)
set_optimizer_attribute(model, "algorithm", :LD_SLSQP)
@variable(model, x, start=2)
set_lower_bound(x,1)
register(model, :f, 1, f, autodiff = true)
@NLobjective(model, Max, f(x))
JuMP.optimize!(model)
```

This code will fail due to the `@assert` in the objective function. I tried this same example using Ipopt.jl and this problem does not arise, which leads me to believe it is caused by NLopt. Is this behavior intentional? It has certainly caused me some headaches today.

**Comment by stevengj** [comment]
The underlying NLopt library should never evaluate the objective function outside of the box domain (though it may evaluate at infeasible points if you have nonlinear constraints), nor does it evaluate the function before optimization begins.

Maybe there is a problem with the JuMP wrappers?

cc @blegat

**Comment by JGSuw** [comment]
I have not tried calling it without the JuMP interface, but I will try that next!
