### ISSUE TITLE
Document non thread-safety

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaOpt/NLopt.jl#186]
Burned myself with this one with `Threads.@spawn` multithreading.

The `Opt` object is not thread-safe, and reusing it leads to problems.

I'd argue this is enough of a footgun that possibly NLopt.jl could try to detect if the same Opt object is being used simultaneously by multiple threads.

Could a flag be added to struct Opt that is set to true when accepted by optimize and false just before returning? And if the flag is already true, emit a warning or error? I suppose you'd also need a try/catch/finally to ensure it's reset to false even if there's an internal exception or interrupt.

(Accidentally posted in an unrelated issue).

**Comment by odow** [comment]
Here's a similar issue with a example using pmap https://github.com/JuliaOpt/NLopt.jl/issues/146

**Comment by odow** [comment]
This is tricky because it's not just `optimize` that is affected. It's everything. (You could easily imagine a scenario where the two threads don't call optimize at the same time, but one changes a property and then the other gets the "wrong" solution.)

We could perhaps document the lack of thread safety. But really, you probably shouldn't expect that a library that calls out to C is thread safe from Julia.

**Comment by BioTurboNick** [comment]
Documenting would be helpful. I don't work with C enough to have the intuition that an input is going to be directly modified by the C library.

**Comment by odow** [comment]
Exactly how did you try to use multi-threading? Was it the NLopt version of https://jump.dev/JuMP.jl/stable/tutorials/algorithms/parallelism/#Using-parallelism-the-wrong-way?

Or did you do something like https://jump.dev/JuMP.jl/stable/tutorials/algorithms/parallelism/#With-multi-threading

**Comment by odow** [comment]
Because if you use a different `Opt` on each thread, then NLopt (the C library) should be threadsafe?

**Comment by BioTurboNick** [comment]
I used the same `Opt`, because as far as I could tell is was just a bucket of settings and not also storing modifiable state used internally.

**Comment by odow** [comment]
> because as far as I could tell it was just a bucket of settings and not also storing modifiable state used internally

This is the problem :smile: We do store modifiable state on the C side of `opt::Ptr{Cvoid}`.

**Comment by odow** [comment]
See https://github.com/JuliaOpt/NLopt.jl/pull/236
