### ISSUE TITLE
ArgumentError: invalid NLopt arguments: invalid algorithm for constraints

### ISSUE THREAD

**Issue by ydereboy** [JuliaOpt/NLopt.jl#188]
Hello, I would greatly appreciate some help

I am trying to define the inequality constraints for the p-median problem. which states x_ij < y_i forall i and j.

I tried to do it with both vector valued and regular constraints. Both gives the same error. I use windows. Let me show you both the vector-valued and the regular way I tried respectively.
```jl
function inEQ(result::Vector, x::Vector, grad::Matrix)
    if length(grad) > 0
        for i in 1:22500
            a = zeros(22650)
            a[i] = 1
            if mod(i,150) > 0
                a[22500+mod(i,150)] = -1
            else
                a[22650] = -1
            end
            grad[:,i] = a
        end
    end
    result[:] = vec(reshape(reshape(x,150,150) .- x[22501:22650],22500,1))
end

inequality_constraint!(opt, (result, x, grad) -> inEQ(result, x, grad), zeros(22500) .+ 1e-8)
```
This is the vector valued constraint version. Here is the regular version with a for loop:
```jl
function inEQ_1(x::Vector, grad::Vector, index_x, index_y)
    if length(grad) > 0
        grad[150*(index_x-1) + index_y] = 1
        grad[22500 + index_y] = -1
        grad[Not(150*(index_x-1) + index_y, 22500 + index_y)] .= 0
    end
    return x[150*(index_x-1) + index_y] - x[22500 + index_y]
end
      
for i in 1:150
    for j in 1:150
        inequality_constraint!(opt, (x,g) -> inEQ_1(x,g,j,i), 1e-8)
    end
end
```
Both gives the same Argument error. Could you please send me to the right direction

Thank you so much in advance..

**Comment by mzaffalon** [comment]
`inequality_constraint!` takes a function of two arguments like this: `function myconstraint(x::Vector, grad::Vector)`, so both of your constraints fail.

Could you please wrap your code with triple backticks (\```) for more readability?

**Comment by mzaffalon** [comment]
> I hope this helps.

Backticks, not single quotation marks.

Sorry, I have misread your second example. That should be correct except for `Not` in `grad[Not(150*(index_x-1) + index_y, 22500 + index_y)] .= 0`.

**Comment by ydereboy** [comment]
Thanks again for the help. But I changed the Not() and I still get the same error. I also don't understand why Not() would cause an error. It is from a julia package called InvertedIndices and helps me slice an array with exclusion. I mean ofcourse it might because of a reason I don't understand but I just don't understand it. Any how I changed the code and built it with out the Not() but I still get the same error. Let me share it with you:

```
function inEQ_1(x::Vector, grad::Vector, index_x, index_y)
    if length(grad) > 0
        grad[150*(index_x-1) + index_y] = 1
        grad[22500 + index_y] = -1
        grad[1:150*(index_x-1) + index_y - 1] .= 0
        grad[150*(index_x-1) + index_y + 1:22500 + index_y - 1] .= 0
        grad[22500 + index_y + 1:22650] .= 0
    end
    return x[150*(index_x-1) + index_y] - x[22500 + index_y]
end

```

With this code I run the same for loop as above. Let me share the whole error with you too:

ArgumentError: invalid NLopt arguments: invalid algorithm for constraints

Stacktrace:
 [1] chk(o::Opt, result::Result)
   @ NLopt C:\Users\suuser\.julia\packages\NLopt\OIUOZ\src\NLopt.jl:211
 [2] inequality_constraint!(o::Opt, f::Function, tol::Float64)
   @ NLopt C:\Users\suuser\.julia\packages\NLopt\OIUOZ\src\NLopt.jl:422
 [3] top-level scope
   @ In[35]:3
 [4] eval
   @ .\boot.jl:373 [inlined]
 [5] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1196

I hope this helps. Thank you

**Comment by mzaffalon** [comment]
> ArgumentError: invalid NLopt arguments: invalid algorithm for constraints
It looks like you are using an algorithm that does not support constraints. What algorithm are you using?

I didn't know about `Not`, thank you.

**Comment by ydereboy** [comment]
Ofcourse my pleasure. Thank you for teaching me about backsticks. I am using L-BFGS. Let me share the whole code:

```
function myFunc(x::Vector, grad::Vector, cost::Vector)
    if length(grad) > 0
        grad[1:22500] = cost
        grad[22501:22650] = 1000000*x[22501:22650] ./ (10000*x[22501:22650].^2 .+ 1).^2
    end
    return sum(cost.*x[1:22500]) + sum(500*x[22501:22650].^2 ./ (10*x[22501:22650] .+ 0.001))
end

opt = Opt(:LD_LBFGS, 22650)
opt.lower_bounds = 0
opt.upper_bounds = 1
opt.xtol_rel = 1e-4

min_objective!(opt, (x, grad) -> myFunc(x,grad,cost))

```
This code works.

Let me share the loop and the constraints with backstick for readability:

```
function inEQ_1(x::Vector, grad::Vector, index_x, index_y)
    if length(grad) > 0
        grad[150*(index_x-1) + index_y] = 1
        grad[22500 + index_y] = -1
        grad[1:150*(index_x-1) + index_y - 1] .= 0
        grad[150*(index_x-1) + index_y + 1:22500 + index_y - 1] .= 0
        grad[22500 + index_y + 1:22650] .= 0
    end
    return x[150*(index_x-1) + index_y] - x[22500 + index_y]
end

for i in 1:150
    for j in 1:150
        inequality_constraint!(opt, (x,g) -> inEQ_1(x,g,j,i), 1e-8)
    end
end

````

I get the error I posted when I run the loop.

**Comment by mzaffalon** [comment]
It looks like `LBFGS` does not support non linear inequality constraints: https://nlopt.readthedocs.io/en/latest/NLopt_Reference/#nonlinear-constraints. Could you try `COBYLA` instead?

**Comment by ydereboy** [comment]
Oh it works with COBYLA. But this is very weird no? Because my constraints are not nonlinear. Indeed they are extremely linear. Constraints giving me the error is (x_ij  < y_i forall i,j.). Is there a problem with my code or something?

**Comment by mzaffalon** [comment]
You are right, your constraints are linear. The documentation does not mention linear constraints except for box constraints.

**Comment by ydereboy** [comment]
I see thank you so much again for your help it was of great help. But maybe final question if you could:) Knowing that my constraints are linear and my objective function are non-linear and the problem is continuous what would your algorithm suggestion be? Again I appreciate the help a lot. It was very important

**Comment by ydereboy** [comment]
I checked the documentation and decided that I want to use Augmented Lagrangian. This requires me to set local_optimizer. But I did not get how to do it from the documentation.  Is there any chance you can show me how to do it?

**Comment by mzaffalon** [comment]
I have never used the augmented Lagrangian myself: the only thing I can do is to refer you to the documentation:
https://nlopt.readthedocs.io/en/latest/NLopt_Algorithms/#augmented-lagrangian-algorithm and https://nlopt.readthedocs.io/en/latest/NLopt_Reference/#localsubsidiary-optimization-algorithm. It looks like the local subsidiary optimization algorithm is set up exactly in the same way you would do for a standard optimization.

Next time you have general questions, I suggest posting to https://discourse.julialang.org/, where the visibility is also higher.

**Comment by stevengj** [comment]
I would probably use a CCSA algorithm.

**Comment by stevengj** [comment]
> Because my constraints are not nonlinear. Indeed they are extremely linear.

NLopt doesn't know that — it has no API specific to linear constraints (except for box constraints), so it assumes that all inequality constraints that you pass are nonlinear.   In any case, LBFGS only supports box constraints.

**Comment by ydereboy** [comment]
I have problem with the Augmented Lagrangian Method. With my syntax algorithm does not move and gets a forced stop. I am almost sure problem is with the setting of the local optimizer. I am not very familiar with the Julia syntax. let me give you my code:

````
function myFunc(x::Vector, grad::Vector, cost::Vector)
    if length(grad) > 0
        grad[1:22500] = cost
        grad[22501:22650] = 1000000*x[22501:22650] ./ (10000*x[22501:22650].^2 .+ 1).^2
    end
    return sum(cost.*x[1:22500]) + 50*sum(10*x[22501:22650].^2 ./ (10*x[22501:22650] .+ 0.001))
end

function inEQ_1(x::Vector, grad::Vector, index_x, index_y)
    if length(grad) > 0
        grad[150*(index_x-1) + index_y] = 1
        grad[22500 + index_y] = -1
        grad[Not(150*(index_x-1) + index_y, 22500 + index_y)] .= 0
    end
    x[150*(index_x-1) + index_y] - x[22500 + index_y]
end

function EQ_1(x::Vector, grad::Vector, index_x)
    if length(grad) > 0
        grad[150*(index_x-1)+1:150*index_x] .= 1
        grad[Not(150*(index_x-1)+1:150*index_x)] .= 0
    end
    sum(x[150*(index_x-1)+1:150*index_x]) - 1
end

function EQ_k(x::Vector, grad::Vector)
    if length(grad) > 0
        grad[1:22500] .= 0
        grad[22501:22650] .= 1
    end
    sum(grad[22501:22650]) - 3
end

opt = Opt(:LD_AUGLAG_EQ, 22650)
opt.lower_bounds = 0
opt.upper_bounds = 1
opt.xtol_rel = 1e-4

min_objective!(opt, (x, grad) -> myFunc(x,grad,cost))

opt.local_optimizer = Opt(:LD_MMA, 22650)

for i in 1:150
    for j in 1:150
        inequality_constraint!(opt, (x,g) -> inEQ_1(x,g,j,i), 1e-8)
    end
end

for i in 1:150
    equality_constraint!(opt, (x,g) -> EQ_1(x,g,i), 1e-8)
end
equality_constraint!(opt, (x,g) -> EQ_k(x,g), 1e-8)

(minf,minx,ret) = optimize(opt, zeros(22650) .+ 1/150)

```
This gives me the output:

(Inf, [0.006666666666666667, 0.006666666666666667, 0.006666666666666667, 0.006666666666666667, 0.006666666666666667, 0.006666666666666667, 0.006666666666666667, 0.006666666666666667, 0.006666666666666667, 0.006666666666666667  …  0.006666666666666667, 0.006666666666666667, 0.006666666666666667, 0.006666666666666667, 0.006666666666666667, 0.006666666666666667, 0.006666666666666667, 0.006666666666666667, 0.006666666666666667, 0.006666666666666667], :FORCED_STOP)

These values are the starting point. Could you please show me how to code this correctly. I believe minor changes are required but I don't know what they are
