### ISSUE TITLE
Maxtime and compilation

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaOpt/NLopt.jl#190]
I'm setting `maxtime` to avoid an occasional infinite cycle on some inputs, but it triggers during the first execution due to compilation of the objective function.

**Comment by odow** [comment]
What would you expect to happen? I don't think NLopt can tell whether the time is because of a long-running function, or because of compilation. It can only terminate once `maxtime` has passed. If it's a problem, you could evaluate the objective once before calling NLopt?

**Comment by BioTurboNick** [comment]
That's fair; if Julia had the ability to track non-compilation elapsed time, NLopt.jl could detect this condition and try again.

**Comment by stevengj** [comment]
No, the maxtime is actually based on a feature from the NLopt C library — it is just wall-clock time.

Mainly, I find it useful for global optimization (where there aren't good stopping criteria), e.g. "give me the best possible result in 3 hours".  But usually in this situation the `maxtime` is huge compared to any conceivable compilation time.

**Comment by BioTurboNick** [comment]
I understand it's used by NLopt C library, but the Julia library could handle the exceptional condition specific to Julia.

I've used it just recently when most optimizations take less than a second and occasionally runs for minutes at a time to keep the total time to a manageable level.

**Comment by odow** [comment]
> If it's a problem, you could evaluate the objective once before calling NLopt?

Did you consider doing this? Or run NLopt twice? Once with a time limit of `0.0` and once with your larger time limit?

**Comment by BioTurboNick** [comment]
Sure I could. That's just annoying 😆

**Comment by stevengj** [comment]
You could also just use `maxeval` instead.
