### ISSUE TITLE
Linking to preinstalled nlopt binaries

### ISSUE THREAD

**Issue by smartalecH** [JuliaOpt/NLopt.jl#196]
I'm on a system where I can't use the normal package manager to install packages.

But luckily, on this system, I've already got the shared `.so` libraries for `nlopt` installed. Is there a way I could simply tell `Nlopt.jl` to look "here" for these libraries and call them that way?

**Comment by gaurav-arya** [comment]
https://jump.dev/JuMP.jl/stable/developers/custom_solver_binaries/ might help

**Comment by stevengj** [comment]
In particular, [Overrides.toml](https://jump.dev/JuMP.jl/stable/developers/custom_solver_binaries/#Overriding-an-entire-artifact) seems like the easiest approach.  It looks like you can just add a line:
```toml
# Override for NLopt_jll
079eb43efd8e547899662cf3e3edb778 = "/foo/bar"
```
to `~/.julia/artifacts/Overrides.toml`, where `/foo/bar/lib/libnlopt.so` is the location of your `libnlopt`?

**Comment by odow** [comment]
Closing because the Overrides.toml is the way to go about this. This is also documented to a lesser extent in the offial Pkg documentation: https://pkgdocs.julialang.org/v1/artifacts/#Overriding-artifact-locations
