### ISSUE TITLE
ReInitCache() error

### ISSUE THREAD

**Issue by elbert5770** [JuliaOpt/NLopt.jl#197]
I saw this error when running the NLopt.LD_LBFGS() example from the Optimization.jl docs.  I didn't capture the error output.  Restarting Julia fixed the issue.  I tried to reproduce with a fresh environment, but could not get the error again.  Julia 1.9.0-rc1, 
[4e6fcdb7] OptimizationNLopt v0.1.5.  Leaving this here so future users will know to restart Julia.

**Comment by stevengj** [comment]
Not actionable if it is not reproducible.
