### ISSUE TITLE
Should support for `MathOptInterface` be moved to an extension?

### ISSUE THREAD

**Issue by palday** [JuliaOpt/NLopt.jl#203]
Some examination of `@time_imports` for MixedModels.jl showed that `MathOptInterface` is one of our largest/slowest imports, even though we don't actually use and just use the NLopt 'native' interface.

I can do the legwork if this sounds reasonable.

cc @dmbates

**Comment by jw3126** [comment]
Same here I want to solve a tiny problem that does not need MOI, yet right now I have to pay for its precomilation and loading.

**Comment by stevengj** [comment]
Sounds good to me.

**Comment by mlubin** [comment]
How can we do this without breaking JuMP+NLopt users on Julia pre 1.9? We need to support at least the latest LTS (1.6).

**Comment by palday** [comment]
@mlubin one option would be to have this change be a breaking release that is otherwise compatible with the current release series but with a higher julia compat bound. Then it's straightforward to backport fixes, etc. and when the next LTS is declared, we drop support for the current series.

**Comment by palday** [comment]
@mlubin there's also this: https://pkgdocs.julialang.org/v1/creating-packages/#Transition-from-normal-dependency-to-extension

**Comment by blegat** [comment]
> Then it's straightforward to backport fixes,

I wouldn't say that, it's best to keep the compatibility for v1.6 in master
