### ISSUE TITLE
GPU Capabilities?

### ISSUE THREAD

**Issue by bdas123** [JuliaOpt/NLopt.jl#209]
Can NLopt be integrated with CUDA.jl?

**Comment by odow** [comment]
NLopt does not have explicit support for GPUs in the solvers it provides.

But your objective and constraint functions could include calls to a GPU, provided you implement the requisite derivative oracles, etc. If you encounter any issues, please post on the Julia discourse forum: https://discourse.julialang.org/c/domain/opt/13
