### ISSUE TITLE
Deal with dsyn in fwi_objective

### ISSUE THREAD

**Issue by venividivici666** [JuliaOpt/NLopt.jl#216]
when I use fwi_objective(model0, q, d_obs; misfit=misfit), how can I process the modeling forward waveform (dsyn)? I try to precess the waveform in my misfit, but I cannot use dsyn.data (type Array has no field data). Thanks a lot!

**Comment by stevengj** [comment]
You really aren't providing enough information to help you.  None of the functions or objects you mention (`fwi_objective` or `dsyn`) are part of the NLopt API, so it sounds like you are asking about some other software package.

**Comment by venividivici666** [comment]
I mean when I try “FWI with user provided misfit function”notebook, I want to process the dsyn, but fwi_objective(model0, q[i], d_obs[i]; misfit=misfit) don’t process the dsyn, and when I process the dsyn in my misfit function, there will show an error like what I have mentioned before. So I want to know whether I should modify fwi_objective function to input the dsyn after I processed. Thank you!

---- Replied Message ----
| From | Steven G. ***@***.***> |
| Date | 03/29/2024 21:18 |
| To | ***@***.***> |
| Cc | venividivici666 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [JuliaOpt/NLopt.jl] Deal with dsyn in fwi_objective (Issue #216) |

You really aren't providing enough information to help you. None of the functions or objects you mention (fwi_objective or dsyn) are part of the NLopt API, so it sounds like you are asking about some other software package.

**Comment by stevengj** [comment]
I don't know what notebook you are referring to.  It isn't part of this package.

**Comment by odow** [comment]
Closing because this doesn't appear to be related to NLopt.jl.

If you have Julia-related questions, please post on the discourse forum: https://discourse.julialang.org
