### ISSUE TITLE
Add support for optional arguments

### ISSUE THREAD

**Issue by jdtuck** [JuliaOpt/NLopt.jl#27]
Can you please add support to pass in arguments to the optimization function to fully support as in the C interfaace of f_data, i.e.,

```
void nlopt::opt::set_min_objective(nlopt::vfunc f, void* f_data);
```

Thanks

**Comment by amitkpal** [comment]
Hi, could you please help me in in understanding how to pass supporting data in nlopt in Python? I have a function f(x,grad,inp), where I want to maximize f w.r.t. x using derivative free algorithms, such as COBYLA, and inp is the input data. I am doing 

opt=nlopt.opt(nlopt.LN_COBYLA,n)
opt.set_lower_bounds(lower_bounds)
opt.set_upper_bounds(upper_bounds)
opt.set_max_objective(f,inp)
v=opt.optimize(x0)

where x0 is the initial guess. However, it is showing 

def set_max_objective(self, *args): return _nlopt.opt_set_max_objective(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'opt_set_max_objective'.

I guess that I am passing the extra input data in a wrong way. Please help.

**Comment by stevengj** [comment]
@amitkpal, there is an example of this in the [NLopt Python tutorial](http://ab-initio.mit.edu/wiki/index.php/NLopt_Tutorial#Example_in_Python).  Do `opt.set_max_objective(lambda x,grad: f(x,grad,inp))`
