### ISSUE TITLE
Zero length gradient passed to target (local_optimizer!)

### ISSUE THREAD

**Issue by felixjung** [JuliaOpt/NLopt.jl#32]
Hi,

I'm trying to implement an optimization using the Multi-Level Single-Linkage (MLSL) global optimization algorithm of NLopt. The algorithm splits the parameter space into smaller sub-spaces and runs a possibly gradient based algorithm on each sub-space. According to the NLopt manual, I should specify the algorithm used in the local optimization via the ``nlopt_opt_set_local_optimizer`` function in the C API. I figured this would be the same as calling ``local_optimizer!(opt::Opt, local_opt::Opt)`` in the Julia API. Here's some rudimentary example code for maximizing the [Shubert function](http://www.sfu.ca/~ssurjano/shubert.html):
```julia
using NLopt

function shubert(x::Vector, grad::Vector)
    println("Gradient vector length: $(length(grad))")
    println("Parameter vector length: $(length(x))")
    ## Compute gradient elements
    grad[1] = (cos(1 + 2*x[2]) + 2*cos(2 + 3*x[2]) + 3*cos(3 + 4*x[2]) + 4*cos(4 + 5*x[2]) + 5*cos(5 + 6*x[2]))*
     (-2*sin(1 + 2*x[1]) - 6*sin(2 + 3*x[1]) - 12*sin(3 + 4*x[1]) - 20*sin(4 + 5*x[1]) - 30*sin(5 + 6*x[1]))

    grad[2] = (cos(1 + 2*x[1]) + 2*cos(2 + 3*x[1]) + 3*cos(3 + 4*x[1]) + 4*cos(4 + 5*x[1]) + 5*cos(5 + 6*x[1]))*
    (-2*sin(1 + 2*x[2]) - 6*sin(2 + 3*x[2]) - 12*sin(3 + 4*x[2]) - 20*sin(4 + 5*x[2]) - 30*sin(5 + 6*x[2]))

    ## Compute target
    target = (cos(1 + 2*x[1]) + 2*cos(2 + 3*x[1]) + 3*cos(3 + 4*x[1]) + 4*cos(4 + 5*x[1]) + 5*cos(5 + 6*x[1]))*
       (cos(1 + 2*x[2]) + 2*cos(2 + 3*x[2]) + 3*cos(3 + 4*x[2]) + 4*cos(4 + 5*x[2]) + 5*cos(5 + 6*x[2]))

    ## Print info
    println("Target: $target")
    println("Gradient: $grad")

    ## Return target
    return target
end

## Configure global optimization
opt = Opt(:G_MLSL_LDS, 2)
lower_bounds!(opt, [-3, -3])
upper_bounds!(opt, [3, 3])

## Configure local optimization
opt_local = Opt(:LD_TNEWTON_PRECOND_RESTART, 2)
local_optimizer!(opt, opt_local)
vector_storage!(opt, 10)

max_objective!(opt, shubert)
optimize(opt, [3., 3.])
```
The corresponding output is this:
```
julia> include("shubert.jl")
Gradient vector length: 0
Parameter vector length: 2
in callback catch
ERROR: BoundsError()
 in shubert at /Users/Felix/Desktop/shubert.jl:7
 in nlopt_callback_wrapper at /Users/Felix/.julia/v0.3/NLopt/src/NLopt.jl:410
 in optimize! at /Users/Felix/.julia/v0.3/NLopt/src/NLopt.jl:509
 in optimize at /Users/Felix/.julia/v0.3/NLopt/src/NLopt.jl:515
 in include at /Applications/Julia-0.3.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.5.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/Felix/Desktop/shubert.jl, in expression starting on line 36

julia>
```
As you can see, NLopt seems to pass a zero-length gradient vector to my target function. As a result Julia throws the ``BoundsError()``. Do you have any idea why this is happening? Am I doing something wrong?

Apart from this. I'd be happy to stick with the MathProgBase API. Unfortunately, I don't know whether I can then use MLSL with some specific local optimization algorithm.

Thanks in advance,

Felix

**Comment by mlubin** [comment]
@feju, you can call ``local_optimizer!`` on ``m.opt`` where ``m`` is an ``NLoptMathProgModel`` object after calling ``loadnonlinearproblem!``. Also happy to accept a PR to expose this through the standard MathProgBase solver options format.

Regarding the ``BoundsError``, I believe you should only try to fill the gradient if it has nonzero length, see the example in the readme.

**Comment by feju** [comment]
Thanks for the reply, Miles. I was just about to close this issue, since I figured the gradient part out myself. I'll definitely check the MathProgBase solution!

**Comment by felixjung** [comment]
@mlubin Any docs for the standard MathProgBase solver options format?

**Comment by mlubin** [comment]
They're just keyword arguments to the solver object: https://github.com/JuliaOpt/NLopt.jl/blob/e7a4a2821dcd20d61941a57db723949f2134baf6/src/NLoptSolverInterface.jl#L20. The names of the parameters are solver dependent, so you could name this ``local_optimizer``.

**Comment by felixjung** [comment]
Cool. Might take a look soonish.

**Comment by stevengj** [comment]
Yes, as you apparently figured out, just because you use a gradient-based algorithm does not mean that NLopt evaluates using a gradient on every function evaluation; it should use gradients on most of the function evaluations, but occasionally it will just request the function value (by passing a zero-length gradient).
