### ISSUE TITLE
Installation needs superuser rights

### ISSUE THREAD

**Issue by mschauer** [JuliaOpt/NLopt.jl#34]
Can I provide a local directory in $LD_LIBRARY_PATH ?

**Comment by mlubin** [comment]
Just comment out the line:
```
provides(AptGet, "libnlopt0", libnlopt)
```
in ``deps/build.jl`` and run ``Pkg.build("NLopt")``. I've never been a big fan of Bindeps piggybacking on apt-get.

**Comment by mschauer** [comment]
Thank you for the fast response, this worked.
