### ISSUE TITLE
Regression from 0.4 compared to 0.3?

### ISSUE THREAD

**Issue by pagnani** [JuliaOpt/NLopt.jl#37]
I'm using NLopt for a pseudolikelihood maximization optimization (thanks for the package ... it works great!) . Now the function to optimize is long to write down here (in particular the gradient), but I observe a regression from 0.3 and 0.4:

```
Version 0.3.10-pre+4 (2015-06-04 13:19 UTC)
Commit c8804e8* (10 days old release-0.3)
x86_64-apple-darwin14.3.0

site = 1	 pll = 2.0597	 time(s) = 0.5386	exit status = FTOL_REACHED
site = 2	 pll = 2.0424	 time(s) = 0.4302	exit status = FTOL_REACHED
site = 3	 pll = 2.0432	 time(s) = 0.4318	exit status = FTOL_REACHED
site = 4	 pll = 2.0466	 time(s) = 0.4539	exit status = FTOL_REACHED
site = 5	 pll = 2.0432	 time(s) = 0.4434	exit status = FTOL_REACHED
site = 6	 pll = 2.0533	 time(s) = 0.4360	exit status = FTOL_REACHED
site = 7	 pll = 2.0469	 time(s) = 0.4386	exit status = FTOL_REACHED
site = 8	 pll = 2.0437	 time(s) = 0.4366	exit status = FTOL_REACHED
site = 9	 pll = 2.0522	 time(s) = 0.4228	exit status = FTOL_REACHED
site = 10	 pll = 2.0357	 time(s) = 0.4359	exit status = FTOL_REACHED


Version 0.4.0-dev+5383 (2015-06-15 08:27 UTC)
Commit 993adea* (0 days old master)
x86_64-apple-darwin14.3.0

site = 1	 pll = 2.0597	 time(s) = 2.3384	exit status = FTOL_REACHED
site = 2	 pll = 2.0424	 time(s) = 2.0590	exit status = FTOL_REACHED
site = 3	 pll = 2.0432	 time(s) = 2.1551	exit status = FTOL_REACHED
site = 4	 pll = 2.0466	 time(s) = 2.2462	exit status = FTOL_REACHED
site = 5	 pll = 2.0432	 time(s) = 2.1300	exit status = FTOL_REACHED
site = 6	 pll = 2.0533	 time(s) = 2.1375	exit status = FTOL_REACHED
site = 7	 pll = 2.0469	 time(s) = 2.3989	exit status = FTOL_REACHED
site = 8	 pll = 2.0437	 time(s) = 7.8286	exit status = FTOL_REACHED
site = 9	 pll = 2.0522	 time(s) = 2.0911	exit status = FTOL_REACHED
site = 10	 pll = 2.0357	 time(s) = 2.1382	exit status = FTOL_REACHED
```

As you can see the timing is much larger in 0.4 although the pseudolikelihood is the same between the two releases (also the solution  vector within numerical precision). I know 0.4 is undergoing lots of changes and before start digging into the problem I wanted to know if there is any usual suspect you might address me to. BTHW I' using `:LD_LBFGS` optimization. 

Also I can stick to 0.3 for the time being waiting a more consolidated 0.4 release.

Thanks again for making NLopt available in julia

**Comment by stevengj** [comment]
Probably the first thing to try would be to see whether the problem is in your objective, not NLopt.  i.e. just try evaluating your objective function a bunch of times in a loop (inside a function) and see if the timing changes a lot in 0.4.

**Comment by pagnani** [comment]
Thanks. Meanwhile, somehow the regression disappeared!!! It was probably related to some of the ongoing massive changes occurring now in 0.4. A comparative profiling I did before the regression disappeared pointed to something related to array indexing but I had no time to investigate further

Sorry for the noise and thanks again!

A

**Comment by stevengj** [comment]
Glad it is resolved!
