### ISSUE TITLE
Failed install on RedHat

### ISSUE THREAD

**Issue by slundberg** [JuliaOpt/NLopt.jl#38]
Perhaps I am missing something simple. But when running `Pkg.add("NLopt")` I get the following build error:

```
File String["/homes/gws/slund1/.julia/v0.3/NLopt/deps/src/nlopt-2.4"] was not created successfully (Tried to run SynchronousStepCollection({`tar xzf /homes/gws/slund1/.julia/v0.3/NLopt/deps/downloads/nlopt-2.4.tar.gz --directory=/homes/gws/slund1/.julia/v0.3/NLopt/deps/src`},"","") )
while loading /homes/gws/slund1/.julia/v0.3/NLopt/deps/build.jl, in expression starting on line 54
```

which I confess I don't understand since `/homes/gws/slund1/.julia/v0.3/NLopt/deps/src/nlopt-2.4` seems to be created. I am using v0.3 and have done a Pkg.update().

**Comment by stevengj** [comment]
I think BinDeps broke recently (JuliaLang/BinDeps.jl#157) and was recently fixed.  You might want to try doing `Pkg.update()` again and then `Pkg.build("NLopt")`.

**Comment by slundberg** [comment]
I saw that BinDeps bumped from v0.3.13 => v0.3.14, but I had already tried that and it didn't change anything. I just tried the master version of BinDeps as well, but that didn't effect the build error.

**Comment by stevengj** [comment]
Can you try removing everything in your `deps/` directory except for `build.jl` and `deps.jl` and trying a fresh `Pkg.build("NLopt")`?

**Comment by slundberg** [comment]
That fixed it, thanks. Previously I had run `Pkg.rm("NLopt")` then `Pkg.add("NLopt")` after the BinDeps update, but that must not have cleared everything.

**Comment by mlubin** [comment]
https://github.com/JuliaLang/julia/issues/7054 strikes again

**Comment by stevengj** [comment]
@mlubin, that's true, but I also think that this is a BinDeps problem: `Pkg.build("Foo")` should force a rebuild of `Foo` even if there are directories there.
