### ISSUE TITLE
Unrecognized function abs`

### ISSUE THREAD

**Issue by zenna** [JuliaOpt/NLopt.jl#39]
I am trying to use NLOpt from JuMP.  Whenever I have tried to use an objective function with `abs` I get

```julia
m_nl = Model(solver=NLoptSolver(algorithm=:LN_COBYLA))
@defVar(m_nl, 0 <= x <= 1)
@setNLObjective(m_nl, :Min, abs(x))
```

```
ERROR: Unrecognized function abs
 in error at ./error.jl:21
```

Surely, at least some of the algorithms should be able to handle expressions with `abs`

**Comment by mlubin** [comment]
This is an issue with JuMP. If your problem is convex, it's almost always better to rewrite ``abs`` with an extra variable and two linear constraints, e.g.,
```
@defVar(m_nl, z)
@addConstraint(m_nl, z >= x)
@addConstraint(m_nl, z >= -x)
@setNLObjective(m_nl, Min, z)
```
Convex.jl does this for you automatically. If you really don't want to introduce extra variables, you can use ``ifelse(x >= 0, x, -x)`` or ``sqrt(x^2)`` instead of ``abs(x)``.

**Comment by zenna** [comment]
I see, generally my problems are not convex.

How is it an issue with JuMP? I wrote a MathProgBase interface to my own nonlinear solver and it handles `abs` ok.

Thanks

**Comment by mlubin** [comment]
JuMP uses [this list](https://github.com/johnmyleswhite/Calculus.jl/blob/360624de4f8619f9266ae9b8f14d7d50c2e11f68/src/differentiate.jl#L117) to help it compute derivatives, and ``abs`` isn't on the list. (Feel free to submit a PR.) Are you sure that ``abs`` was working through JuMP with a different solver?

**Comment by zenna** [comment]
Yes, I wrote the solver and interface myself.

```julia
m_nl = Model(solver=DRealSolver(precision = 0.001))
@defVar(m_nl, 0 <= x <= 1)
@setNLObjective(m_nl, :Min, abs(x))
solve(m)
```

```julia
julia> getValue(x)
0.0
```

**Comment by zenna** [comment]
It does not use any derivative information though

**Comment by mlubin** [comment]
There are two weird things going on:
1. If you don't request any features in the call to ``initialize``, then JuMP shouldn't need to prepare derivatives and hence you wouldn't run into the error.
2. But, the logic for skipping derivative prep seems off. Currently, if you request zero features, it looks like JuMP still tries to prepare derivatives, and hence you should run into the same error as with NLopt.

**Comment by stevengj** [comment]
Closing as not an NLopt issue.

**Comment by mlubin** [comment]
@zenna, feel free to open up an issue on the JuMP side
