### ISSUE TITLE
Okay to drop julia 0.3?

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/NLopt.jl#43]
We have some breaking changes coming to the MathProgBase interface (https://github.com/JuliaOpt/MathProgBase.jl/pull/91) which will have a minimum requirement of Julia 0.4. So updating to the new changes will mean dropping support on ``master`` for Julia 0.3. I'm happy to do all the work, just want to double check that this is okay with you, @stevengj. The next release of NLopt.jl would be tagged as 0.3.0 so that it's still possible to release updates for Julia 0.3 users using 0.2.* tags if needed.

**Comment by stevengj** [comment]
That's fine with me.

**Comment by tkelman** [comment]
closed by #44
