### ISSUE TITLE
"ArgumentError: invalid NLopt arguments" when trying to use the tutorial with G_MLSL

### ISSUE THREAD

**Issue by 315234** [JuliaOpt/NLopt.jl#46]

**Comment by stevengj** [comment]
You have to supply a local optimizer and tolerances for `G_MLSL`.

**Comment by 315234** [comment]
Is this documented anywhere? There don't seem to be any tutorials or test cases for any of the global optimisers. I can't even find examples for the original NLopt package.

**Comment by stevengj** [comment]
It's documented in the NLopt manual under MLSL:

http://ab-initio.mit.edu/wiki/index.php/NLopt_Algorithms#MLSL_.28Multi-Level_Single-Linkage.29

There are tests for the global optimizers in https://github.com/stevengj/nlopt/tree/master/test

**Comment by 315234** [comment]
Thank you
