### ISSUE TITLE
The number of required iterations have changed since April 2015

### ISSUE THREAD

**Issue by KajWiik** [JuliaOpt/NLopt.jl#47]
Update: ignore the question, my bad.. 

I had run the test with tol = 1e-4, with 1e-12 floating point accuracy messed things up. Sorry

--------------------------------

I tested NLopt.jl in April and wrote down the required number of iterations. To my amazement, when I rerun the script now the results were worse by orders of magnitude and the algorithm that was best (and should be!) performed worst. Here is the code:

```julia
using NLopt

count = 0 # keep track of # function evaluations

function myfunc(x::Vector, grad::Vector, datain)

    global count
    count::Int += 1
    return (datain[1] - x[1])^2 + (datain[2] - x[2])^4
    
end

opt = Opt(:LN_COBYLA, 2) # 64
#opt = Opt(:LN_NELDERMEAD, 2) # 86
#opt = Opt(:LN_SBPLX, 2) # 152

xtol_rel!(opt,1e-12)
data = [5.0, 6.0] 
min_objective!(opt, (x, grad) -> myfunc(x, grad, data))

@time (minf,minx,ret) = optimize(opt, [1.234, 5.678])
println("got $minf at $minx after $count iterations (returned $ret)")
```

Here are the results:

Algorithm | Iterations before | Iterations now
-------------- | ------------------- | -------------------
:LN_COBYLA | 64 | 4263263
:LN_NELDERMEAD | 86 | 231
:LN_SBPLX | 152 | 545

I have tested with both Julia v0.3 and v0.4 on Ubuntu 15.10, NLopt version is `libnlopt0:amd64 2.4.2+dfsg-2`

What's happening?

**Comment by stevengj** [comment]
Is it working again?

**Comment by KajWiik** [comment]
Yeah, it was a stupid mistake, I tried with a much smaller tolerance than I
made the benchmarks before. Everything works now as before, i.e. perfectly.

Sorry and thanks,
Kaj
