### ISSUE TITLE
Build failure on OSX when conflicting Homebrew taps exist

### ISSUE THREAD

**Issue by frupaul** [JuliaOpt/NLopt.jl#57]
I'm running Julia 0.4.3 and trying to install NLopt 0.3.2 but got these errors.The version of the osx in my Mac is EI Capitan 10.11.3

```
ERROR: failed process: Process(`/Users/paul/.julia/v0.4/Homebrew/deps/usr/bin/brew install --force-bottle staticfloat/juliadeps/NLopt`, ProcessExited(1)) [1]
```

and this

```
WARNING: NLopt had build errors.

 - packages with build errors remain installed in /Users/paul/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("NLopt")`
 - build a single package by running its `deps/build.jl` script
```

`Pkg.build` fails, (even after a `Pkg.update`). Any hint?

**Comment by alexeymorgunov** [comment]
Has there been any solution to this? I'm experiencing this with both both Julia 0.4.7 and Julia 0.5.0.

**Comment by alexeymorgunov** [comment]
I found a workaround that works, it seems. This was my output when trying to link it manually.
```
/Users/morgunov/.julia/v0.5/Homebrew/deps/usr/bin/brew link staticfloat/juliatranslated/nlopt --force
Linking /Users/morgunov/.julia/v0.5/Homebrew/deps/usr/Cellar/nlopt/2.4.2_2... Error: Formulae found in multiple taps:
 * homebrew/science/nlopt
 * staticfloat/juliatranslated/nlopt

Please use the fully-qualified name e.g. homebrew/science/nlopt to refer the formula.
```

I then did:
```
Users/morgunov/.julia/v0.5/Homebrew/deps/usr/bin/brew untap homebrew/science
/Users/morgunov/.julia/v0.5/Homebrew/deps/usr/bin/brew link staticfloat/juliatranslated/nlopt --force
```
And with that it worked.

**Comment by stevengj** [comment]
@staticfloat, is there a way to tell Homebrew which tap to use, so that users don't get into this situation if they have conflicting taps?  Better yet, automatically prefer the `juliatranslated` tap?

**Comment by mlubin** [comment]
I think a number of julia homebrew packages are broken at the moment: https://github.com/JuliaOpt/SCS.jl/issues/72

**Comment by staticfloat** [comment]
This was a problem with Homebrew; [we are indeed specifying which tap to use](https://github.com/JuliaOpt/NLopt.jl/blob/master/deps/build.jl#L19), but there was a [bug in the `link` step](https://github.com/Homebrew/brew/issues/2288) that ignored this.  It's been fixed now, so please `Homebrew.update()` and try again.

**Comment by odow** [comment]
Closing because we don't use Homebrew to distribute anymore.
