### ISSUE TITLE
MethodError: `parseNLExpr_runtime` has no method matching parseNLExpr_runtime

### ISSUE THREAD

**Issue by leoplct** [JuliaOpt/NLopt.jl#60]
I think the problem is at the last line (@NLobjective(....)) but which is the right way to do it?

> LoadError: MethodError: `parseNLExpr_runtime` has no method matching parseNLExpr_runtime(::JuMP.Model, ::Function, ::Array{ReverseDiffSparse.NodeData,1}, ::Int64, ::Array{Float64,1})
> Closest candidates are:
>   parseNLExpr_runtime(::JuMP.Model, !Matched::Number, ::Any, ::Any, ::Any)
>   parseNLExpr_runtime(::JuMP.Model, !Matched::JuMP.Variable, ::Any, ::Any, ::Any)
>   parseNLExpr_runtime(::JuMP.Model, !Matched::JuMP.NonlinearExpression, ::Any, ::Any, ::Any)
>   ...
>  in include_string at loading.jl:282

```
using JuMP
using NLopt

function functs_MOP4(x::Vector)
	pi = 4.0*atan(1.0)
	n  = length(x)
	f  = zeros(2)
	f[1] = 0.0
	for i = 1:(n-1)
		f[1] = f[1] + (-10.0*exp(-0.20*sqrt(x[i]^2+x[i+1]^2)))
	end
	f[2] = 0.0
	for i = 1:n
		f[2] = f[2] + (abs(x[i])^0.8+5.0*sin(x[i]^3))
	end

	return f
end

function bounds_MOP4()
	return ([-5.0;-5.0;-5.0],[5.0;5.0;5.0])
end

m = Model(solver=NLoptSolver(algorithm=:LD_MMA))
@NLobjective(m, Min, functs_MOP4)
```

**Comment by mlubin** [comment]
There's no support for any sort of vector operations in nonlinear expressions. In this particular case it should be straightforward to rewrite your function using ``@NLexpression`` for each component of ``f``. For the objective, you also need to provide a scalar value.

**Comment by mlubin** [comment]
Also this issue is related to JuMP syntax, not NLopt

**Comment by rt5592** [comment]
Hi
Is there any way to use JuMP with vector inputs to user defined functions? I have looked at several posts from about 1 year ago, e.g. (https://groups.google.com/d/msg/julia-opt/u6JXB56q1KE/b88NNlQwBgAJ),  and was wondering if there have been any changes to JuMP syntax to allow for that.

**Comment by mlubin** [comment]
See a more recent discussion at https://discourse.julialang.org/t/solvers-nonlinear-constraints-and-user-defined-functions/4690/2

**Comment by rt5592** [comment]
Hi
Thanks. I did read that discussion. I have several user defined functions (nested) with data inputs as well. So I'm trying to figure out if I should use MathProgBase NLP function, and skip JuMP altogether
