### ISSUE TITLE
Segfault in LN_SBPLX and LN_NELDERMEAD

### ISSUE THREAD

**Issue by jdrugo** [JuliaOpt/NLopt.jl#64]
If I am running the following code

``` Julia
using NLopt

function optimf(verbose::Bool=true)
    function f(x, g)
        println("Entering f")
        fx = dot(x, x)
        if length(g) > 0
            for i = 1:length(x)
                g[i] = 2x[i]
            end
        end
        println("Leaving f")
        return fx
    end

    opt = Opt(:LN_SBPLX, 2)
    min_objective!(opt, f)
    optf, optx, ret = optimize(opt, [2.0, 3.0])
end

optimf()
```

I get the output

```
$ julia optim_crash_test.jl
Entering f
Leaving f
Entering f
Leaving f
Entering f
Leaving f

signal (11): Segmentation fault: 11
unknown function (ip: 0x0)
Segmentation fault: 11
```

The same happens if I use `LN_NELDERMEAD` instead of `LN_SBPLX`. All other algorithms that I have tested seem to work. The Segfault always happens after 3 function evaluations.

The above happens with a fresh install of NLopt.jl on OS X with Julia 0.4.6:

```
julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> Pkg.status()
1 required packages:
 - NLopt                         0.3.3
7 additional packages:
 - BinDeps                       0.4.5
 - Compat                        0.9.0
 - Homebrew                      0.3.5
 - JSON                          0.7.0
 - MathProgBase                  0.5.5
 - SHA                           0.2.1
 - URIParser                     0.1.6
```

**Comment by jdrugo** [comment]
The same happens on Julia v0.5.0-rc4, fresh installation.

**Comment by pochoi** [comment]
It is Julia 0.4.7 from the official binary for OSX
```
julia> optimf()
Entering f
Leaving f
Entering f
Leaving f
Entering f
Leaving f

signal (11): Segmentation fault: 11
unknown function (ip: 0x0)
Segmentation fault: 11
```
```
julia> versioninfo()
Julia Version 0.4.7
Commit ae26b25 (2016-09-18 16:17 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

It is Julia 0.5.0 from the official binary for OSX
```
julia> optimf()
Entering f
Leaving f
Entering f
Leaving f
Entering f
Leaving f

signal (11): Segmentation fault: 11
while loading no file, in expression starting on line 0
unknown function (ip: 0xffffffffffffffff)
Allocations: 7510706 (Pool: 7509336; Big: 1370); GC: 14
Segmentation fault: 11
```
```
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by kurtuba** [comment]
I have the same problem. I an using the 0.4.7 and 0.5.0 versions and both of them gives the following segmentation fault for LN_NELDERMEAD:

`signal (11): Segmentation fault: 11
while loading no file, in expression starting on line 0
unknown function (ip: 0xffffffffffffffff)
Allocations: 100007015 (Pool: 99739069; Big: 267946); GC: 158
Segmentation fault: 11`

Any idea about how to fix it?

**Comment by jdrugo** [comment]
The above works for me on Linux with Julia 0.4.7 and NLopt.jl 0.3.2. Linux installs nlopt-2.4.0 rather than the nlopt-2.4.2 used by Homebrew.jl on OS X. However, reverting back to nlopt-2.4.0 and NLopt.jl 0.3.2 on OS X does not resolve the issue.

**Comment by stevengj** [comment]
I'm getting similar segfaults, but when I re-compiled NLopt with debugging turned on (configured it with `--enable-debug`) the crash went away, so this may be tricky to track down.

**Comment by Alexander-Barth** [comment]
I am have this error with the algorithm GN_DIRECT on Mac OS X (travis CI) using NLopt.jl v0.3.6 and  https://homebrew.bintray.com/bottles/nlopt-2.4.2_2.sierra.bottle.tar.gz . Is there a global derivative-free algorithm known to work cross-platform?

**Comment by mzaffalon** [comment]
No segfault on Julia v1.1.0 and NLopt v0.5.1.
