### ISSUE TITLE
@NLconstraint, JuMP

### ISSUE THREAD

**Issue by ghost** [JuliaOpt/NLopt.jl#65]
I posted the following MFE on JuliaOpt and it was pointed out by Miles Lubin that it was not "a compilation issue or anything related to JuMP. NLopt or the NLopt/MathProgBase interface is rejecting the problem. You should open an issue at the NLopt repo."
[mfe.zip](https://github.com/JuliaOpt/NLopt.jl/files/474251/mfe.zip)

In the attached .zip file the problem equality constraint is commented with "PROBLEM constraint."

Thanks.

**Comment by odow** [comment]
Closing as stale. I'm now aware of any current issues using NLopt from JuMP.
