### ISSUE TITLE
Load Error using NLopt.jl

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaOpt/NLopt.jl#66]
I have a nonlinear optimization problem that I have been solving using IPOPT. I am interested in seeing the results with other tools, so I am trying NLopt.jl. My problem is fairly large, so I cannot post my code here and currently I am unable to reprodue the error with a simple example. But, my only modification to my code was basically changing the solver:
```
using NLopt
mdl = Model(solver=NLoptSolver(algorithm=:LD_MMA))
```
my code works perfectly fine using IPOPT as a solver, but using NLopt, I get this error:
```
LoadError: ArgumentError: invalid NLopt arguments
 in chk(::Int32) at /home/febbo/.julia/v0.5/NLopt/src/NLopt.jl:259
 in chkn at /home/febbo/.julia/v0.5/NLopt/src/NLopt.jl:277 [inlined]
 in equality_constraint!(::NLopt.Opt, ::Function, ::Array{Float64,1}) at /home/febbo/.julia/v0.5/NLopt/src/NLopt.jl:503
 in loadproblem!(::NLopt.NLoptMathProgModel, ::Int64, ::Int64, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Symbol, ::JuMP.NLPEvaluator) at /home/febbo/.julia/v0.5/NLopt/src/NLoptSolverInterface.jl:155
 in _buildInternalModel_nlp(::JuMP.Model, ::JuMP.ProblemTraits) at /home/febbo/.julia/v0.5/JuMP/src/nlp.jl:1219
 in #build#93(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::JuMP.Model) at /home/febbo/.julia/v0.5/JuMP/src/solvers.jl:314
 in (::JuMP.#kw##build)(::Array{Any,1}, ::JuMP.#build, ::JuMP.Model) at ./<missing>:0
 in #solve#88(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at /home/febbo/.julia/v0.5/JuMP/src/solvers.jl:1...
```

where it is failing on this line:
```
status = solve(mdl)
```
Does anyone have any thoughts on this error? I realize that the small amount of information that I provided may make it difficult to debug this issue, but I am not sure what else to do.

Thank you!

**Comment by odow** [comment]
Do you have an equality constraint in your model? The [`:LD_MMA`](http://ab-initio.mit.edu/wiki/index.php/NLopt_Algorithms#MMA_.28Method_of_Moving_Asymptotes.29_and_CCSA) algorithm only supports inequality constraints.

You could try the [`:LD_SLSQP`](http://ab-initio.mit.edu/wiki/index.php/NLopt_Algorithms#SLSQP) algorithm instead.

**Comment by huckl3b3rry87** [comment]
@odow yes, I had an equality constraint and using the ``:LD_SLSQP`` algorithm makes the model run, but it is not solved to optimality and returns all zeros for the solution. I will look into changing options, like the iteration number etc. to see if that helps.

THanks!
