### ISSUE TITLE
augmented lagrangian

### ISSUE THREAD

**Issue by jotwin** [JuliaOpt/NLopt.jl#74]
I can't get the augmented lagranian algorithm to work because the gradient vector seems to be empty

```
opt = Opt(:LD_AUGLAG, 1)
maxeval!(opt, 1)
ftol_abs!(opt, 1e-3)
opt2 = Opt(:LD_LBFGS, 1)
maxeval!(opt2, 100)
ftol_abs!(opt2, 1e-3)
local_optimizer!(opt, opt2)
max_objective!(opt2, (p, g) -> g[1])
max_objective!(opt, (p, g) -> g[1])
optimize!(opt, [0.0])

in callback catch
ERROR: BoundsError: attempt to access 0-element Array{Float64,1} at index [1]
 in (::##7#8)(::Array{Float64,1}, ::Array{Float64,1}) at ./REPL[20]:1
 in nlopt_callback_wrapper(::UInt32, ::Ptr{Float64}, ::Ptr{Float64}, ::Ptr{Void}) at /home/jakub/.julia/v0.5/NLopt/src/NLopt.jl:427
 in optimize!(::NLopt.Opt, ::Array{Float64,1}) at /home/jakub/.julia/v0.5/NLopt/src/NLopt.jl:526

```

**Comment by axsk** [comment]
I have the same problem, sometimes it works for a couple of function calls, but then it fails.
This is kind of an emergency for me since I need this for my masters thesis, which is due in 1.5 weeks *panic*

**Comment by axsk** [comment]
The `README.md` even explains/suggests that workaround. (As does the original NLopt).

One might automate this using a something along the lines of `Optim.jl`'s `OnceDifferentiable` type, choosing whether to calculate only the function value or the gradient as well based on the need of the optimizer.
