### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by davidzentlermunro** [JuliaOpt/NLopt.jl#77]
I get the following error installing via atom v1.16.0, julia v0.5.0:

```julia
GitError(Code:ENOTFOUND, Class:Repository, Could not find repository from 'NLopt')
 in Base.LibGit2.GitRepo(::String) at .\libgit2\repository.jl:11
 in install(::String, ::String) at .\pkg\write.jl:38
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at .\pkg\entry.jl:530
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at .\pkg\entry.jl:476
 in edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N}) at .\pkg\entry.jl:30
 in (::Base.Pkg.Entry.##2#5{String,Base.Pkg.Types.VersionSet})() at .\task.jl:360
 in sync_end() at task.jl:311
 in macro expansion at task.jl:327 [inlined]
 in add(::String, ::Base.Pkg.Types.VersionSet) at entry.jl:51
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at dir.jl:31
 in add(::String) at pkg.jl:100
 in include_string(::String, ::String) at loading.jl:441
 in eval(::Module, ::Any) at boot.jl:234
 in (::Atom.##65#68)() at eval.jl:102
 in withpath(::Atom.##65#68, ::Void) at utils.jl:30
 in withpath(::Function, ::Void) at eval.jl:38
 in macro expansion at eval.jl:101 [inlined]
 in (::Atom.##64#67{Dict{String,Any}})() at task.jl:60
```

**Comment by stevengj** [comment]
Does installing other packages work?

**Comment by davidzentlermunro** [comment]
yes, other packages installing fine.

**Comment by stevengj** [comment]
Maybe it was a temporary server glitch?  `Pkg.add("NLopt")` works fine for me.

**Comment by davidzentlermunro** [comment]
I'm still getting same issue. Here is a fuller capture of output:
`INFO: Upgrading ForwardDiff: v0.3.5 => v0.4.2    
INFO: Upgrading JuMP: v0.15.1 => v0.16.2
INFO: Upgrading MathProgBase: v0.5.10 => v0.6.4
INFO: Installing NLopt v0.3.4
INFO: Rolling back MathProgBase from v0.6.4 to v0.5.10
INFO: Rolling back JuMP from v0.16.2 to v0.15.1
INFO: Rolling back ForwardDiff from v0.4.2 to v0.3.5
GitError(Code:ENOTFOUND, Class:Repository, Could not find repository from 'NLopt')
in add at base\pkg\pkg.jl:100
in #cd#1 at base\pkg\dir.jl:31
in cd at base\file.jl:48
in #2 at base\pkg\dir.jl:31
in add at base\pkg\entry.jl:51
in macro expansion at base\task.jl:327
in sync_end at base\task.jl:311
GitError(Code:ENOTFOUND, Class:Repository, Could not find repository from 'NLopt')
 in sync_end() at task.jl:311
 in macro expansion at task.jl:327 [inlined]
 in add(::String, ::Base.Pkg.Types.VersionSet) at entry.jl:51
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at dir.jl:31
 in add(::String) at pkg.jl:100
 in include_string(::String, ::String) at loading.jl:441
 in eval(::Module, ::Any) at boot.jl:234
 in (::Atom.##65#68)() at eval.jl:102
 in withpath(::Atom.##65#68, ::Void) at utils.jl:30
 in withpath(::Function, ::Void) at eval.jl:38
 in macro expansion at eval.jl:101 [inlined]
 in (::Atom.##64#67{Dict{String,Any}})() at task.jl:60
`

**Comment by stevengj** [comment]
Sounds like a Pkg problem, not an NLopt problem; you should report it at the main Julia repository.

I'm not sure what all the "rolling back" messages are about.  It is possible that you've pinned your packages at inconsistent versions?  Check `Pkg.status()`.

**Comment by rdeits** [comment]
Actually, I think this is a github problem. CI for https://github.com/RobotLocomotion/drake just went down because it couldn't find the nlopt github repo.

**Comment by rdeits** [comment]
Although I can see the repo just fine from my machine.
