### ISSUE TITLE
Initial step size documentation incorrect

### ISSUE THREAD

**Issue by keatonmill** [JuliaOpt/NLopt.jl#79]
The "Initial Step Size" section of the documentation (https://github.com/JuliaOpt/NLopt.jl#initial-step-size) does not match the actual functions exposed by the package, here:

https://github.com/JuliaOpt/NLopt.jl/blob/master/src/NLopt.jl#L382

```julia
function initial_step(o::Opt, x::Vector{Cdouble}, dx::Vector{Cdouble})
    if length(x) != ndims(o) || length(dx) != ndims(o)
        throw(BoundsError())
    end
    chkn(ccall((:nlopt_get_initial_step,libnlopt),
               Cenum, (_Opt, Ptr{Cdouble}, Ptr{Cdouble}), o, x, dx))
    dx
end
initial_step{T<:Real}(o::Opt, x::AbstractVector{T}) =
    initial_step(o, copy!(Array(Cdouble,length(x)), x),
                 Array(Cdouble, ndims(o)))
```

**Comment by odow** [comment]
> ### Initial step size
>
> Just [as in the C
> API](http://ab-initio.mit.edu/wiki/index.php/NLopt_Reference#Initial_step_size),
> you can set the initial step sizes for derivative-free
> optimization algorithms via the `opt.initial_step` property:
> ```julia
> opt.initial_step = dx
> ```
> Here, `dx` is an array of the (nonzero) initial steps for each
> dimension, or a single number if you wish to use the same initial
> steps for all dimensions. `initial_step(opt::Opt,
> x::AbstractVector)` returns the initial step that will be used for a
> starting guess of `x` in `optimize(opt,x)`.

Docs make sense to me:

```julia
julia> using NLopt

julia> opt = Opt(:LN_COBYLA, 2)
Opt(LN_COBYLA, 2)

julia> opt.initial_step = 0.1
0.1

julia> initial_step(opt, [1.0, 2.0])
2-element Vector{Float64}:
 0.1
 0.1

julia> opt.initial_step = [0.2, 0.3]
2-element Vector{Float64}:
 0.2
 0.3

julia> initial_step(opt, [1.0, 2.0])
2-element Vector{Float64}:
 0.2
 0.3
```

Closing as stale, and because the README is correct.
