### ISSUE TITLE
Signal a new starting point in nested optimization

### ISSUE THREAD

**Issue by rongar9** [JuliaOpt/NLopt.jl#80]
In a nested (global+local) search (e.g. GN_MLSL_LDS with a local search algorithm), can the local optimizer "signal" that it completed its run and that the global optimizer has moved on to a different starting point?
For example, if one would like to know the number of different starting points that the global algorithm went through before it reached MAXTIME?

**Comment by odow** [comment]
I think the answer is "no." NLopt.jl just passes the objective function to the NLopt library in C.

Docs are here: https://nlopt.readthedocs.io/en/latest/NLopt_Algorithms/#mlsl-multi-level-single-linkage

Closing as stale.
