### ISSUE TITLE
Can't download library on windows

### ISSUE THREAD

**Issue by guihigashi** [JuliaOpt/NLopt.jl#82]
can't download from http://ab-initio.mit.edu/nlopt/nlopt-2.4.1-dll32.zip, build fails

**Comment by mmagnuski** [comment]
The same happens for me :(

**Comment by cat-tron** [comment]
Same for me. Is there a way to download the file elsewhere?

**Comment by stevengj** [comment]
What happens if you try to download http://ab-initio.mit.edu/nlopt/nlopt-2.4.1-dll32.zip manually in your browser?

**Comment by ohadle** [comment]
I get:
```
File Transfer Blocked

Transfer of the file you were trying to download or upload has been blocked in accordance with company policy. Please contact your system administrator if you believe this is in error.

File name: libnlopt-0.dll
```

**Comment by stevengj** [comment]
Grrr, I wonder if this is an MIT firewall thing blocking DLLs somehow? 

We're currently in the process of migrating everything off the ab-initio server, and will get to nlopt eventually.

**Comment by stevengj** [comment]
Should hopefully be fixed now on master (changed the URLs to use https://github.com/stevengj/nlopt/releases/tag/nlopt-2.4.2).  Will try to tag today if tests look good.
