### ISSUE TITLE
precompile error

### ISSUE THREAD

**Issue by gkeee** [JuliaOpt/NLopt.jl#92]
I had an error like :  " Failed to precompile NLopt to /.../.juliapro-0.5.1.1/lib/v0.5/NLopt.ji.
while loading ..."
How can i build NLopt from source to have a compiler installed. I did not find NLopt.ji
(I m using Linux.)

**Comment by stevengj** [comment]
What is the complete error output from typing `Pkg.build("NLopt"); using NLopt` in a new Julia session?

**Comment by odow** [comment]
Closing as stale.
