### ISSUE TITLE
Build error - NLopt asks for sudo password despite local installation

### ISSUE THREAD

**Issue by deknapp** [JuliaOpt/NLopt.jl#93]
NLopt asks for a sudo password. My Julia package directory is not in a place where this should be necessary. Where and why does it need a sudo password? I cannot tell from the build script.

**Comment by stevengj** [comment]
You don't say what operating system you are using, but probably it is trying to install the `nlopt` library, e.g. by running `apt-get install libnlopt0` on Ubuntu/Debian GNU/Linux.

If you don't want to do `sudo` during `Pkg.add`, you can always install the nlopt package for your OS separately, before running `Pkg.build`.
