### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by vincentmanz** [JuliaOpt/NLopt.jl#98]
Hi, 
I would like to know why I could not build the package. Thanks!
```
julia> 
[vincem@nhmpc33-227 phylonetworks]$ sudo julia
[sudo] password for vincem: 
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-redhat-linux

julia> Pkg.build("NLopt")
INFO: Building NLopt
==============================================================================[ ERROR: NLopt ]===============================================================================

LoadError: UndefVarError: pushfront! not defined
while loading /root/.julia/v0.6/NLopt/deps/build.jl, in expression starting on line 56

=============================================================================================================================================================================

==============================================================================[ BUILD ERRORS ]===============================================================================

WARNING: NLopt had build errors.

 - packages with build errors remain installed in /root/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("NLopt")`
 - build a single package by running its `deps/build.jl` script

=============================================================================================================================================================================

julia> 

```

**Comment by ngiann** [comment]
Similar here:

Pkg.build("NLopt")
INFO: Building NLopt
INFO: Attempting to create directory /home/giannins/.julia/v0.6/NLopt/deps/downloads
INFO: Directory /home/giannins/.julia/v0.6/NLopt/deps/downloads already exists
INFO: Downloading file https://github.com/stevengj/nlopt/releases/download/nlopt-2.4.2/nlopt-2.4.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) SSL connect error
=======================================================================================================================[ ERROR: NLopt ]=======================================================================================================================

LoadError: failed process: Process(`curl -f -o /home/giannins/.julia/v0.6/NLopt/deps/downloads/nlopt-2.4.2.tar.gz -L https://github.com/stevengj/nlopt/releases/download/nlopt-2.4.2/nlopt-2.4.2.tar.gz`, ProcessExited(35)) [35]
while loading /home/giannins/.julia/v0.6/NLopt/deps/build.jl, in expression starting on line 56

==============================================================================================================================================================================================================================================================

=======================================================================================================================[ BUILD ERRORS ]=======================================================================================================================

WARNING: NLopt had build errors.

 - packages with build errors remain installed in /home/giannins/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("NLopt")`
 - build a single package by running its `deps/build.jl` script

==============================================================================================================================================================================================================================================================

julia>
